In [29]:
file = open('sentences.txt', 'r')

In [30]:
import re
s = file.readline()

Каждая строка в файле соответствует одному предложению. Считайте их, приведите каждую к нижнему регистру с помощью строковой функции lower().


Произведите токенизацию, то есть разбиение текстов на слова. Для этого можно воспользоваться регулярным выражением, которое считает разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t). Не забудьте удалить пустые слова после разделения.

In [31]:
L = []
for line in file:
    L.append(re.split('[^a-z]',line.lower()))


In [32]:
print(L)
print(len(L))

[['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', ''], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', ''], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', '', ''], ['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', '', ''], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that', 'possess', '', '', '', 'chromosomes', 'and', 'roughly', '', '', '', '', '

In [33]:
L4 = []
for line in L:
    for elem in line:
        if elem:
            L4.append(elem)

In [34]:
print(L4)

['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that', 'possess', 'chromosomes', 'and', 'roughly', 'genes', 'domestic', 'cats', 'are', 'similar', 'in', 'size', 'to', 'the', 'other', 'member

Составьте список всех слов, встречающихся в предложениях. Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. Для этого удобно воспользоваться структурой dict.

In [35]:
D = {}

In [36]:
i = 0
for j in L4:
    if j:
        if j not in D:
            D[j] = i
            i = i+1
print(D)

{'displays': 146, 'osx': 185, 'selection': 58, 'safari': 214, 'just': 18, 'developed': 187, 'over': 161, 'vermin': 63, 'domestic': 78, 'major': 243, 'installed': 174, 'symbols': 140, 'through': 199, 'human': 41, 'using': 134, 'disk': 237, 'its': 65, 'fifth': 242, 'features': 245, 'tamed': 55, 'upgrade': 225, 'lb': 88, 'drive': 241, 'to': 12, 'won': 232, 'deliberately': 54, 'marks': 219, 'has': 120, 'predecessor': 164, 'non': 192, 'which': 175, 'read': 113, 'catenates': 3, 'october': 151, 'every': 208, 'os': 166, 'they': 59, 'world': 133, 'now': 188, 'possess': 74, 'intel': 182, 'keyboards': 107, 'bytes': 6, 'unnecessary': 93, 'patch': 210, 'predators': 62, 'small': 50, 'output': 28, 'entirely': 228, 'where': 16, 'ears': 42, 'available': 155, 'right': 123, 'often': 104, 'sequence': 19, 'some': 169, 'lion': 195, 'frequency': 40, 'are': 69, 'year': 209, 'download': 198, 'terms': 114, 'concern': 98, 'error': 97, 'for': 24, 'pipes': 119, 'since': 180, 'factory': 173, 'artificial': 57, 'cont

In [37]:
print(len(L4))
print(max(D.values()))
print(D['in'])

470
247
39


In [38]:
import numpy as np

In [39]:
print(len(L))

21


Создайте матрицу размера n d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 254.

In [40]:
matrix = np.zeros((22, 254))
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [41]:
k = 0 
for line in L:
    for elem in line:
        if elem:
            #print(elem)
            matrix[k, D[elem]] = matrix[k, D[elem]] + 1
            #print(matrix[k, D[elem]], elem)
    k = k+1
    
    

In [42]:
print(np.sum(matrix))

470.0


In [43]:
print(matrix)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [44]:
print(matrix[0,:])
print(L[0])

[1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', '']

In [45]:
import scipy
from scipy import spatial

In [46]:
u = np.array(matrix[0,:])

In [47]:
v = np.array(matrix[0,:])

Найдите косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine. Какие номера у двух предложений, ближайших к нему по этому расстоянию (строки нумеруются с нуля)? Эти два числа и будут ответами на задание.

In [48]:
scipy.spatial.distance.cosine(u, v)

0.0

In [49]:
E = []
for i in range(22):
    u = matrix[0,:]
    v = matrix[i,:]
    print(scipy.spatial.distance.cosine(u, v))
    E.append(scipy.spatial.distance.cosine(u, v))

0.0
0.7908349933664811
0.9306624754718463
0.8156975548063786
0.9604715292478953
0.8939339828220179
0.950970966215454
0.7958758547680685
0.71875
0.8894185328838271
0.841886116991581
0.7525126265847084
0.8713760611431184
0.9583333333333334
0.7788370657676543
0.894590744661054
0.8852921330647191
0.9262790219225514
0.9631395109612757
0.9653312377359232
0.8842724875284311
nan


In [50]:
print(E)

[0.0, 0.7908349933664811, 0.9306624754718463, 0.8156975548063786, 0.9604715292478953, 0.8939339828220179, 0.950970966215454, 0.7958758547680685, 0.71875, 0.8894185328838271, 0.841886116991581, 0.7525126265847084, 0.8713760611431184, 0.9583333333333334, 0.7788370657676543, 0.894590744661054, 0.8852921330647191, 0.9262790219225514, 0.9631395109612757, 0.9653312377359232, 0.8842724875284311, nan]


In [51]:
print(sorted(E,reverse = True))

[0.9653312377359232, 0.9631395109612757, 0.9604715292478953, 0.9583333333333334, 0.950970966215454, 0.9306624754718463, 0.9262790219225514, 0.894590744661054, 0.8939339828220179, 0.8894185328838271, 0.8852921330647191, 0.8842724875284311, 0.8713760611431184, 0.841886116991581, 0.8156975548063786, 0.7958758547680685, 0.7908349933664811, 0.7788370657676543, 0.7525126265847084, 0.71875, 0.0, nan]
