In [21]:
import sklearn
import numpy as np
from sklearn import datasets, model_selection

In [38]:
digits = datasets.load_digits()
breast_cancer= datasets.load_breast_cancer()
print(breast_cancer.data)
print(digits.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [14]:
X1 = digits.data
y1 = digits.target
X2 = breast_cancer.data
y2 = breast_cancer.target

In [13]:
from sklearn.cross_validation import cross_val_score

C:\Users\ARTEM\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [15]:
def write_ans(filename, score):
    with open(filename, 'w') as f_out:
        f_out.write(str(score))

In [19]:
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

In [20]:
bern = BernoulliNB()
mult = MultinomialNB()
gaus = GaussianNB()

In [28]:
ans1 = cross_val_score(bern, X1, y1, scoring = 'accuracy')
print"bern: ", np.mean(ans1)
ans2 = cross_val_score(mult, X1, y1, scoring = 'accuracy')
print "mult: ", np.mean(ans2)
ans3 = cross_val_score(gaus, X1, y1, scoring = 'accuracy')
print "gaus: ", np.mean(ans3)

bern:  0.8258236507780582
mult:  0.8708771489735053
gaus:  0.8186003803550138


In [29]:
ans4 = cross_val_score(bern, X2, y2, scoring = 'accuracy')
print"bern: ", np.mean(ans4)
ans5 = cross_val_score(mult, X2, y2, scoring = 'accuracy')
print "mult: ", np.mean(ans5)
ans6 = cross_val_score(gaus, X2, y2, scoring = 'accuracy')
print "gaus: ", np.mean(ans6)

bern:  0.6274204028589994
mult:  0.8945790401930752
gaus:  0.9367492806089297


In [42]:
write_ans("zad_1.txt", np.mean(ans6))
write_ans("zad_2.txt", np.mean(ans2))